---
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled  

- name: Disabling firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false

- name: Contained configuration modules
  ansible.builtin.copy:
    src: modules-k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: 0644
    force: true

- name: Set modprobe overlay
  ansible.builtin.command: "modprobe overlay"

- name: Set modprobe br_netfilter
  ansible.builtin.command: "modprobe br_netfilter"

- name: Remove swapfile from /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^/dev/mapper/cs-swap'

- name: Contained configuration sysctl
  ansible.builtin.copy:
    src: sysctl-k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644
    force: true

- name: add global DNS entry in resolv config file
  ansible.builtin.blockinfile:
    path: /etc/resolv.conf
    insertafter: EOF
    block: "nameserver {{ dns_ip }}"

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  ignore_errors: true

- name: Reboot hosts
  ansible.builtin.reboot: 
