---
- name: Ensure system-packages are installed
  ansible.builtin.dnf:
    name: "{{ system_packages }}"
    state: present

- name: Config Docker repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0640

- name: Ensure docker packages are installed
  ansible.builtin.dnf:
    name: "{{ docker_packages }}"
    state: present

- name: Contained configuration
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0644
    force: true

- name: Ensure docker service is enabled and started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ docker_svc }}"
