---
- name: Check nodes status
  ansible.builtin.command: kubectl get nodes -o wide
  register: getnodes
  when: inventory_hostname in groups['control-plane-primary']

- name: Show check status
  ansible.builtin.debug:
    msg: "{{getnodes.stdout_lines}}"
  when: inventory_hostname in groups['control-plane-primary']

- ansible.builtin.debug:
    msg:
    - "* * * * * * * * *"
    - ""
    - "CONGRATULATION, your Kubernetes platform is ready to enjoy"
    - ""
    - "* * * * * * * * *"
  when: inventory_hostname in groups['control-plane-primary']
